### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by charlotteForever** [zxyang625/C-_MYSQL_DATABASE#2]
想问下校友的qt版本是什么，开发工具是VS吗

**Comment by zxyang625** [comment]
你好，大版本是Qt5，开发工具用的是Visual Studio 2019，VS中可以安装Qt的工具，这样就不需要再下载Qt的开发包了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxyang625/MYSQL_DATABASE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 晚上9:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zxyang625/MYSQL_DATABASE] 请教几个问题 (Issue #2)





 
想问下校友的qt版本是什么，开发工具是VS吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
